### ISSUE TITLE
Is there a way to automate the build and reload part?

### ISSUE THREAD

**Issue by shubham234** [hindmost/cra-template-complex-browserext-typescript#3]
It's a pain currently to rebuild the project every time after making small changes. Haven't been able to figure out how to setup automatic builds and reload on Chrome. If you/somebody knows how is it doable then please let me know and can it be added to the template?

**Comment by hindmost** [comment]
https://stackoverflow.com/questions/42772860/how-to-make-create-react-app-auto-build
